server:
  port: 8003

spring:
  application:
    name: eureka-consume

#management:
 # security:
#    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/

feign:
  hystrix:
    enabled: true

security:
  oauth2:
    resource:
      id: eureka-consume
      user-info-uri: http://localhost:8088/sso/user/me
      prefer-token-info: false